language: java

jdk:
 - oraclejdk8
 - oraclejdk9

sudo: required

dist: trusty

group: edge

cache:
  directories:
  - $HOME/.m2

script: mvn package -DskipTests=true -B

addons:
  apt:
    packages: oracle-java9-installer
